### ISSUE TITLE
The command to set the subscription in the script output is wrong

### ISSUE THREAD

**Issue by skidrow88** [hausec/PowerZure#1]
Hello,

There is a mistake in the script output when you did not set a subscription.

The script output is currently the following:
```
Please set your default subscription with 'Set-Subscription --subscription {id}
```

However the good one is this one:
```
Set-Subscription -Id {id}
```
or 
```
az account set --subscription {id}
```

Thank you

**Comment by hausec** [comment]
Good catch, updated. Thanks!
