### ISSUE TITLE
Ideas - audit public resources

### ISSUE THREAD

**Issue by yellow-starburst** [hausec/PowerZure#12]
Absolutely phenomenal tool!
What do you think about adding more public searching of resources to powerzure?
So for example Powerzure would query:
- Public storage - Blobs, tables, etc. 
- Virtual machines with public IP 
- sql databases 
etc.

**Comment by hausec** [comment]
The idea of PowerZure is to script together multiple cmdlets together in the existing Azure PS modules, e.g. uploading a payload and executing it. Enumeration of blobs, VMs, VNICs, DBs, etc. all have single cmdlets that already exist in the Az PowerShell module, so it wouldn't make much sense to just have them as "wrapper" functions in PowerZure unless I was chaining multiple cmdlets together. If you have an idea of what cmdlets can be chained together to give you output or functionality beyond a single cmdlet, I'm open to those suggestions.
