### ISSUE TITLE
Add-AzureSPSecret fails 

### ISSUE THREAD

**Issue by biy1** [hausec/PowerZure#20]
Microsoft renamed `.objectId` to `.id`. 
So the code at line 1611 would have to be adjusted to `$Uri = 'https://graph.microsoft.com/beta/applications/' + $App.id + '/addPassword'`. There might be other places where this breaks functionality..

**Comment by biy1** [comment]
Oh, and apparently `.ApplicationId` got renamed to `.AppId`. Thus line 1618 would have to be adjusted as well..

**Comment by hausec** [comment]
Fixed, thank you!
