### ISSUE TITLE
Cannot convert null to type "System.DateTime"

### ISSUE THREAD

**Issue by 3isenHeiM** [hausec/PowerZure#4]
Thanks for the tool, very promising :)

I ran into this issue while testing it...

```
PS C:\Users\user\Desktop> Import-Module .\PowerZure.ps1
New-PSGetItemInfo : Cannot convert null to type "System.DateTime".
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2253 char:102
                         + ... ach-Object {New-PSGetItemInfo -SoftwareIdentity $_ -Type $script:PSAr ...
                         +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                 + CategoryInfo          : MetadataError: (:) [New-PSGetItemInfo],
ArgumentTransformationMetadataException
+ FullyQualifiedErrorId : RuntimeException,New-PSGetItemInfo     
```

Do you have any idea ?

**Comment by hausec** [comment]
Are you still having this issue? It looks related to your PowerShell setup

**Comment by 3isenHeiM** [comment]
I'm still having the issue.
I cannot find where in my PS setup would such an error be thrown...

**Comment by hausec** [comment]
Sorry, had multiple people test this and it looks like it's an error with your PS instance

**Comment by cyberfreaq** [comment]
I have the same issue. @3isenHeiM were you able to solve this?

**Comment by cyberfreaq** [comment]
Okay, this was easy:
https://www.ictstuff.info/get-installedmodule-returns-system-datetime-error/

After updating you need to close the Powershell window and open a new one.
